# Generated by Django 3.2 on 2021-04-24 12:47

import Matieres.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatiereScolaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeDeFichier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fichiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('theme', models.CharField(max_length=100)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='media/fichiersdeposes'), upload_to=Matieres.models.my_upload_to)),
                ('matiereLinked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matieres.matierescolaire')),
                ('typeDoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matieres.typedefichier')),
            ],
        ),
    ]
