# Generated by Django 3.2 on 2021-04-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matieres', '0002_anneearchivee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anneearchivee',
            old_name='year',
            new_name='date',
        ),
    ]
