# Generated by Django 3.2 on 2021-04-25 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Matieres', '0003_rename_year_anneearchivee_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='matierescolaire',
            name='annee',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='Matieres.anneearchivee'),
            preserve_default=False,
        ),
    ]
