# Generated by Django 3.2 on 2021-05-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matieres', '0004_matierescolaire_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneearchivee',
            name='date',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='typedefichier',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
